#!/usr/bin/env python3

# TODO
import sys
import helpers
import re
from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile @screen_name")
    elif not (re.match('@', sys.argv[1])):
        sys.exit("Usage: ./smile @screen_name")

    # get screen_name's tweets
    tweets = helpers.get_user_timeline(re.sub(r'@?','',sys.argv[1]), 50)
    if tweets == None:
        sys.exit("it is impossible to tweets")
    
    # instantiate analyzer
    analyzer = Analyzer()
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        message =str(int(score)) + " " + tweet 
        if score > 0.0:
            print(colored(message, "green"))
        elif score < 0.0:
            print(colored(message, "red"))
        else:
            print(colored(message, "yellow"))


if __name__ == "__main__":
    main()
